---
credentials:     
  - name: secrets.yml
    credential_type: Vault
    inputs:
      vault_password: "Astro@1312"  
  - name: privateKey    
    credential_type: Machine
    state: present      
  - name: ds_creds
    credential_type: Machine DS
    inputs:     
         username: ""
         password: ""  
    state: present     
  - name: vcenter_creds
    credential_type: VMware vCenter
    inputs:
      host: ""
      username: ""
      password: ""
    state: present
    
  - name: aix   
    credential_type: Machine
    state: present        
        
        
      
 
 
     
    
# === EXAMPLES ===

# NOTE:
# the full parameter list for credentials may be found in /roles/configure_credential/README.md

#credentials:
# Remove test_credential_1 from AAP
#   - name: test_credential_1
#     state: absent
#
# Create a machine credential called test_credential_2
#   - name: test_credential_2
#     description: test_credential_2 for machine access
#     credential_type: machine # this is the default value if not provided
#
# Create test_credential_3 by copying test_credential_2
#   - name: test_credential_3
#     copy_from: test_credential_2
#     description: test_credential_3 for machine access
